<?php

/*
 | (c) copyright 2024 - MillionVisions
 */

namespace MillionVisions\LaravelI18n\Enums;

/**
 * ISO 639-2
 *
 * Enum representing ISO 639-2 language codes.
 */
enum ISO639_2: string
{
    case ABA = 'aba';  // Ab Abkhaz
    case ACE = 'ace';  // Acehnese
    case ACH = 'ach';  // Acholi
    case ADA = 'ada';  // Adangme
    case ADF = 'adf';  // Aromanian
    case AEH = 'aeh';  // Aeta
    case AGA = 'aga';  // Aghem
    case AIN = 'ain';  // Ainu
    case AKI = 'aki';  // Akira
    case ALD = 'ald';  // Aleut
    case ALS = 'als';  // Alemannic
    case AMH = 'amh';  // Amharic
    case ARA = 'ara';  // Arabic
    case ARB = 'arb';  // Arabic (Modern Standard)
    case ARC = 'arc';  // Aramaic
    case ARM = 'arm';  // Armenian
    case ASH = 'ash';  // Ashaninka
    case ASM = 'asm';  // Assamese
    case AST = 'ast';  // Asturian
    case AVA = 'ava';  // Avar
    case AVE = 'ave';  // Avestan
    case AYM = 'aym';  // Aymara
    case AZE = 'aze';  // Azerbaijani
    case BAK = 'bak';  // Bashkir
    case BAM = 'bam';  // Bambara
    case BAN = 'ban';  // Balinese
    case BAR = 'bar';  // Bavarian
    case BAS = 'bas';  // Basa
    case BEL = 'bel';  // Belarusian
    case BEN = 'ben';  // Bengali
    case BIH = 'bih';  // Bihari
    case BOD = 'bod';  // Tibetan
    case BOS = 'bos';  // Bosnian
    case BRE = 'bre';  // Breton
    case BUL = 'bul';  // Bulgarian
    case CAT = 'cat';  // Catalan
    case CHE = 'che';  // Chechen
    case CHI = 'chi';  // Chinese
    case CHR = 'chr';  // Cherokee
    case CHU = 'chu';  // Church Slavic
    case CHV = 'chv';  // Chuvash
    case COR = 'cor';  // Cornish
    case COS = 'cos';  // Corsican
    case CRH = 'crh';  // Crimean Tatar
    case CRO = 'cro';  // Croatian
    case CZE = 'cze';  // Czech
    case DAK = 'dak';  // Dakota
    case DAN = 'dan';  // Danish
    case DEO = 'deu';  // German
    case DRA = 'dra';  // Dravidian
    case DUA = 'dua';  // Duala
    case DUT = 'dut';  // Dutch
    case DZO = 'dzo';  // Dzongkha
    case EAE = 'eae';  // East Anglian English
    case EGY = 'egy';  // Egyptian
    case EWE = 'ewe';  // Ewe
    case FAO = 'fao';  // Faroese
    case FIJ = 'fij';  // Fijian
    case FIN = 'fin';  // Finnish
    case FRA = 'fra';  // French
    case FRE = 'fre';  // French
    case FUL = 'ful';  // Fulah
    case GAL = 'gal';  // Galician
    case GEO = 'geo';  // Georgian
    case GER = 'ger';  // German
    case GLA = 'gla';  // Scottish Gaelic
    case GLE = 'gle';  // Irish
    case GLG = 'glg';  // Galician
    case GRE = 'gre';  // Greek
    case GUA = 'gua';  // Guarani
    case GUJ = 'guj';  // Gujarati
    case HAT = 'hat';  // Haitian
    case HAU = 'hau';  // Hausa
    case HEB = 'heb';  // Hebrew
    case HIN = 'hin';  // Hindi
    case HIR = 'hir';  // Hiri Motu
    case HUN = 'hun';  // Hungarian
    case HYM = 'hym';  // Hymn
    case IBO = 'ibo';  // Igbo
    case IDO = 'ido';  // Ido
    case IND = 'ind';  // Indonesian
    case IRO = 'iro';  // Iroquois
    case ITA = 'ita';  // Italian
    case JAV = 'jav';  // Javanese
    case JPN = 'jpn';  // Japanese
    case KAC = 'kac';  // Kachin
    case KAL = 'kal';  // Kalaallisut
    case KAN = 'kan';  // Kannada
    case KAS = 'kas';  // Kashmiri
    case KAZ = 'kaz';  // Kazakh
    case KHM = 'khm';  // Khmer
    case KIK = 'kik';  // Kikuyu
    case KIR = 'kir';  // Kirghiz
    case KMB = 'kmb';  // Kimbundu
    case KOR = 'kor';  // Korean
    case KUR = 'kur';  // Kurdish
    case LAO = 'lao';  // Lao
    case LAT = 'lat';  // Latin
    case LAV = 'lav';  // Latvian
    case LIN = 'lin';  // Lingala
    case LIT = 'lit';  // Lithuanian
    case LUB = 'lub';  // Luba-Katanga
    case LUG = 'lug';  // Ganda
    case MAC = 'mac';  // Macedonian
    case MAH = 'mah';  // Marshallese
    case MAI = 'mai';  // Maithili
    case MAL = 'mal';  // Malayalam
    case MAM = 'mam';  // Mam
    case MAN = 'man';  // Mandinka
    case MAO = 'mao';  // Maori
    case MAR = 'mar';  // Marathi
    case MAS = 'mas';  // Masai
    case MDH = 'mdh';  // Hmong Daw
    case MEL = 'mel';  // Melanesian
    case MLG = 'mlg';  // Malagasy
    case MLT = 'mlt';  // Maltese
    case MNC = 'mnc';  // Manchu
    case MNI = 'mni';  // Manipuri
    case MOD = 'mod';  // Modo
    case MOL = 'mol';  // Moldavian
    case MON = 'mon';  // Mongolian
    case MOZ = 'moz';  // Mozambican
    case NAA = 'naa';  // Nauruan
    case NAV = 'nav';  // Navajo
    case NEP = 'nep';  // Nepali
    case NIG = 'nig';  // Niger-Congo
    case NOR = 'nor';  // Norwegian
    case OBC = 'obc';  // Old English
    case ODS = 'ods';  // Old Danish
    case OLI = 'oli';  // Oltenian
    case ORI = 'ori';  // Oriya
    case OSH = 'osh';  // Ossetian
    case OTA = 'ota';  // Ottoman Turkish
    case PAA = 'paa';  // Papuan
    case PAI = 'pai';  // Paiwan
    case PAM = 'pam';  // Pampanga
    case PAN = 'pan';  // Punjabi
    case PAP = 'pap';  // Papiamento
    case PAS = 'pas';  // Pashto
    case PER = 'per';  // Persian
    case PHI = 'phi';  // Philippine
    case POL = 'pol';  // Polish
    case POR = 'por';  // Portuguese
    case QUE = 'que';  // Quechua
    case RAR = 'rar';  // Rarotongan
    case RHA = 'rha';  // Rhaeto-Romance
    case ROM = 'rom';  // Romani
    case RUS = 'rus';  // Russian
    case SAA = 'saa';  // Saanich
    case SAG = 'sag';  // Sango
    case SAN = 'san';  // Sanskrit
    case SED = 'sed';  // Sedang
    case SGA = 'sga';  // Old Irish
    case SGN = 'sgn';  // Sign Languages
    case SHI = 'shi';  // Tachelhit
    case SIN = 'sin';  // Sinhalese
    case SKA = 'ska';  // Sika
    case SLA = 'sla';  // Slavic
    case SLO = 'slo';  // Slovak
    case SLV = 'slv';  // Slovenian
    case SOM = 'som';  // Somali
    case SOT = 'sot';  // Sotho
    case SPA = 'spa';  // Spanish
    case SRI = 'sri';  // Srilankan
    case SUK = 'suk';  // Sukuma
    case SUN = 'sun';  // Sundanese
    case SWA = 'swa';  // Swahili
    case SWE = 'swe';  // Swedish
    case TAG = 'tag';  // Tagalog
    case TAH = 'tah';  // Tahitian
    case TAM = 'tam';  // Tamil
    case TAT = 'tat';  // Tatar
    case TEL = 'tel';  // Telugu
    case THA = 'tha';  // Thai
    case TIG = 'tig';  // Tigrinya
    case TIR = 'tir';  // Tigrinya
    case TKT = 'tkt';  // Tok Pisin
    case TLI = 'tli';  // Tlingit
    case TOG = 'tog';  // Tonga
    case TPI = 'tpi';  // Tok Pisin
    case TRK = 'trk';  // Turkic
    case TRM = 'trm';  // Turkish
    case TSI = 'tsi';  // Tswana
    case TSO = 'tso';  // Tswana
    case TWI = 'twi';  // Twi
    case UIG = 'uig';  // Uighur
    case ULA = 'ula';  // Ulaangom
    case UKR = 'ukr';  // Ukrainian
    case URD = 'urd';  // Urdu
    case UZB = 'uzb';  // Uzbek
    case VEN = 'ven';  // Venda
    case VIE = 'vie';  // Vietnamese
    case VOL = 'vol';  // Volapük
    case WAA = 'waa';  // Waal
    case WAL = 'wal';  // Walamo
    case WAM = 'wam';  // Wam
    case WAR = 'war';  // Waray
    case WEL = 'wel';  // Welsh
    case WOL = 'wol';  // Wolof
    case XAL = 'xal';  // Kalmyk
    case XHO = 'xho';  // Xhosa
    case YID = 'yid';  // Yiddish
    case YOR = 'yor';  // Yoruba
    case ZHA = 'zha';  // Zhuang
    case ZUL = 'zul';  // Zulu
}
